### ISSUE TITLE
summary.txt erroneous stats

### ISSUE THREAD

**Issue by thetwoj** [THADEUSH123/design-transformer#2]
```
12770534.8 meters is the longest link.
0.0 meters is the shortest link.
```
Almost 8k miles LOL

Can't handle trees but the curvature of the earth is nbd 👍 

```
==Material Requirements==
0 primary devices required.
0 secondary devices required.
28 client node devices required.
28 odroid devices required.
```
326 links but no primary/secondary devices required?

**Comment by thetwoj** [comment]
@THADEUSH123 clarified that these output issues are due to input data integrity, lots of work to be done around input validation

**Comment by THADEUSH123** [comment]
I semi-fixed the longest link issue. It will still default to 0.0 coordinates are never defined, but the script will now display the longest link for root causing the data input issue. I also added the Site class to better handle input validation, rather than the geoJSON encoding for objects in the data store.

I think this resolves this issue, but may still need to do some more data validation.

==Data Summary==
  279 unique sites imported.
  325 unique links imported.

  "11K311_11L101" is the longest link at 391.9m.
  "12L962_12L967" is the shortest link at 6.7m.

==Material Requirements==
This section includes information based on what was defined in the "bill_of_materials" field of the input data set.
251 of 279 sites ARE MISSING this data. This will affect results.

0 primary devices required.
0 secondary devices required.
28 client node devices required.
28 odroid devices required.
